CREATE USER postgres SUPERUSER;
CREATE DATABASE postgres WITH OWNER postgres;
CREATE USER recipeman WITH PASSWORD 'password';
CREATE DATABASE Recipe;
GRANT ALL PRIVILEGES ON DATABASE Recipe TO recipeman;